# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zBP4qOfYOtrKX096JeQel_RFxMO5-KIo
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
from mlxtend.preprocessing import minmax_scaling
np.random.seed(0)

orginal_data= np.random.exponential(size=1000)
scaled_data=minmax_scaling(orginal_data,columns=[0])
'''
plt.figure(figsize=(6,6))
plt.xlabel("badimcan")
plt.ylabel("biber") '''
fig, ax = plt.subplots(1, 2, figsize=(15, 3))
sns.histplot(orginal_data, ax=ax[0], kde=True, legend=True)
ax[0].set_title("Original Data")
sns.histplot(scaled_data, ax=ax[1], kde=True, legend=False)
ax[1].set_title("Scaled data")
plt.show()

normalize_data=stats.boxcox(orginal_data)
fig, ax=plt.subplots(1,2, figsize=(15,3))
sns.histplot(orginal_data,ax=ax[0], kde=True,legend= False )
ax[0].set_title("Original Data")
sns.histplot(normalized_data[0], ax=ax[1], kde=True, legend =False)
ax[1].set_title("Normalized Data")
plt.show()

# normalize the exponential data with boxcox
normalized_data = stats.boxcox(orginal_data)

# plot both together to compare
fig, ax=plt.subplots(1, 2, figsize=(15, 3))
sns.histplot(orginal_data, ax=ax[0], kde=True, legend=False)
ax[0].set_title("Original Data")
sns.histplot(normalized_data[0], ax=ax[1], kde=True, legend=False)
ax[1].set_title("Normalized data")
plt.show()